# Enable (turn on) specific servers ONLY
#"edgebus.runtime.server.indexes" = "management publisher subscriber"

# Enable (turn on) specific endpoints ONLY
#"edgebus.runtime.endpoint.indexes" = "info management publisher subscriber"


# Configure web server "management"
[[edgebus.runtime.server]]
	index = "management"
	listenHost = "0.0.0.0"
	listenPort = "8443"
	type = "https"
# /Configure web server "management"

# Configure web server "publisher"
[[edgebus.runtime.server]]
	index = "publisher"
	listenHost = "0.0.0.0"
	listenPort = "8444"
	type = "https"
# /Configure web server "publisher"

# Configure web server "subscriber"
[[edgebus.runtime.server]]
	index = "subscriber"
	listenHost = "0.0.0.0"
	listenPort = "8445"
	type = "https"
# /Configure web server "subscriber"


# Configure endpoint "info"
[[edgebus.runtime.endpoint]]
	index = "info"
	type = "rest-info"
	servers = "management publisher subscriber"
	bindPath = "/info"
	[edgebus.runtime.endpoint.info.cors]
		methods = "GET"
		whiteList = "*"
		allowedHeaders = "*"
# /Configure endpoint "info"

# Configure endpoint "management"
[[edgebus.runtime.endpoint]]
	index = "management"
	type = "rest-management"
	servers = "management"
	bindPath = "/management"
	methods = "GET"
# /Configure endpoint "management"

# Configure endpoint "publisher"
[[edgebus.runtime.endpoint]]
	index = "publisher"
	type = "rest-publisher"
	servers = "publisher"
	bindPath = "/publisher"
	methods = "GET"
# /Configure endpoint "publisher"

# Configure endpoint "subscriber"
[[edgebus.runtime.endpoint]]
	index = "subscriber"
	type = "rest-subscriber"
	servers = "subscriber"
	bindPath = "/subscriber"
	methods = "GET"
# /Configure endpoint "subscriber"


# Cache URL (Redis only at the moment)
[edgebus.runtime.cache]
	url = "redis://your.redis.server:6379/0"
# /Cache URL (Redis only at the moment)


# Persistent storage URL (Postgres only at the moment)
[edgebus.runtime.persist]
	url = "postgres://your.postgres.server:5432/notifier"
# /Persistent storage URL (Postgres only at the moment)


# =======================
# Database Migration only
# =======================

# Persistent storage URL (Postgres only at the moment)
[edgebus.initialize.database]
	url = "postgres://your.postgres.server:5432/notifier"
# /Persistent storage URL (Postgres only at the moment)
