# Enable (turn on) specific topics ONLY
#"edgebus.setup.topic.indexes" = "..."

# Enable (turn on) specific publishers ONLY
#"edgebus.setup.publisher.indexes" = "..."

# Enable (turn on) specific subscribers ONLY
#"edgebus.setup.subscriber.indexes" = "..."

# Setup topic "TOPCcdaa9b7d6c16484bb2a5a6d58c78c2c6"
[[edgebus.setup.topic]]
	index = "TOPCcdaa9b7d6c16484bb2a5a6d58c78c2c6"
	description = "PSS Provider WTF2 callbacks"
# /Setup topic "TOPCcdaa9b7d6c16484bb2a5a6d58c78c2c6"

# Setup topic "TOPC44e5b80b06f1447ebf38b6ab2c84c84a"
[[edgebus.setup.topic]]
	index = "TOPC44e5b80b06f1447ebf38b6ab2c84c84a"
	"description" = "WTF2 callbacks"
# /Setup topic "TOPC44e5b80b06f1447ebf38b6ab2c84c84a"


# Setup HTTP-host publisher "PUBR9028c57498b641988fc71355e9ac622e"
[[edgebus.setup.publisher]]
	index = "PUBR9028c57498b641988fc71355e9ac622e"
	type = "http_host"
	path = "/v2/callback/cryptoproviders/pss-provider-wtf2"
	target_topic = "TOPCcdaa9b7d6c16484bb2a5a6d58c78c2c6"
# /Setup HTTP-host publisher "PUBR9028c57498b641988fc71355e9ac622e"

# Setup HTTP-host publisher "PUBRafb0ff9b217d4a5c8b33d76291bb7d81"
[[edgebus.setup.publisher]]
	index = "PUBRafb0ff9b217d4a5c8b33d76291bb7d81"
	type = "http_host"
	path = "/v2/callback/cryptoproviders/wtf2"
	target_topic = "TOPC44e5b80b06f1447ebf38b6ab2c84c84a"
# /Setup HTTP-host publisher "PUBRafb0ff9b217d4a5c8b33d76291bb7d81"


# Setup Websocket-host subscriber "SUBR319ef1447b054a5292acecf40345b89b"
[[edgebus.setup.subscriber]]
	index = "SUBR319ef1447b054a5292acecf40345b89b"
	type = "websocket_host"
	source_topics = "TOPCcdaa9b7d6c16484bb2a5a6d58c78c2c6 TOPC44e5b80b06f1447ebf38b6ab2c84c84a"
# /Setup Websocket-host subscriber "SUBR319ef1447b054a5292acecf40345b89b"

# Setup Websocket-host subscriber "SUBR707ef6997dc64f79b7449d599a36c5fd"
[[edgebus.setup.subscriber]]
	index = "SUBR707ef6997dc64f79b7449d599a36c5fd"
	type = "websocket_host"
	source_topics = "TOPCcdaa9b7d6c16484bb2a5a6d58c78c2c6 TOPC44e5b80b06f1447ebf38b6ab2c84c84a"
# /Setup Websocket-host subscriber "SUBR707ef6997dc64f79b7449d599a36c5fd"

# Setup HTTP-client subscriber "SUBRec84237fe6674a15820407ab5a93e97b"
[[edgebus.setup.subscriber]]
	index = "SUBRec84237fe6674a15820407ab5a93e97b"
	type = "http_client"
	http_method="POST"
	http_url="http://127.0.0.1:8020/v2/callback/cryptoproviders/pss-provider-wtf2"
	source_topics = "TOPCcdaa9b7d6c16484bb2a5a6d58c78c2c6"
# /Setup Websocket-host subscriber "SUBRec84237fe6674a15820407ab5a93e97b"

