#
# docker-compose --file database/docker-compose.yaml up
# docker-compose --file database/docker-compose.yaml down
#

version: '3.9'
networks:
  default:
    name: "edgebus-local-tier"

services:
  http-dump:
    image: theanurin/http-dump
    restart: always
    environment:
      - DUMP_FILE=true
      - DUMP_STDOUT=true
    volumes:
      - ../.http-dump.local:/data
    ports:
      - 127.0.0.1:52003:8080

  postgres:
    image: theanurin/devel.postgres-13:13.11.1
    restart: always
    networks:
      - default
    ports:
      - 127.0.0.1:52000:5432

  pgadmin4:
    depends_on:
      - postgres
    networks:
      - default
    image: dpage/pgadmin4:7.6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@edgebus.io
      - PGADMIN_DEFAULT_PASSWORD=devel
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
    - 127.0.0.1:52010:80

  redis:
    image: redis:7.0.11-alpine
    networks:
      - default
    ports:
      - 127.0.0.1:52001:6379/tcp
    # command: >
    #   --appendonly yes
    #   --requirepass 'password'

  redis-commander:
    image: rediscommander/redis-commander@sha256:19cd0c49f418779fa2822a0496c5e6516d0c792effc39ed20089e6268477e40a
    depends_on:
      - redis
    networks:
      - default
    ports:
      - 127.0.0.1:52011:8081/tcp
    environment:
      - REDIS_HOSTS=EdgeBus:redis:6379:0
